<a href="https://colab.research.google.com/github/richdied/Python_Data_Analytics_and_Visualization/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a0 = np.array(9)

In [ ]:
print(a0)

9


In [ ]:
a1 = np.array([1,3,5,7,9])

In [ ]:
print(a1)

[1 3 5 7 9]


In [ ]:
a2 = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])

In [ ]:
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
a3 = np.array([[[1, 2],
                [3, 4]],
               [[5, 6],
                [7, 8]],
               [[9, 10],
                [11, 12]]])

In [ ]:
print(a3)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [ ]:
AR = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [ ]:
print(AR)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
AR.shape

(12,)

In [ ]:
AR.size

12

In [ ]:
AR.ndim

1

In [ ]:
AR2 = AR.reshape(3,4)

In [ ]:
print(AR2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
AR2.shape

(3, 4)

In [ ]:
AR2.size

12

In [ ]:
AR2.ndim

2

In [ ]:
AR3 = AR.reshape(3,2,2)

In [ ]:
print(AR3)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [ ]:
AR3.shape

(3, 2, 2)

In [ ]:
AR3.size

12

In [ ]:
AR3.ndim

3

In [ ]:
AR.reshape(-1,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [ ]:
AR2.reshape(1,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [ ]:
AR3.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
AR3.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
a3 + 100

array([[[101, 102],
        [103, 104]],

       [[105, 106],
        [107, 108]],

       [[109, 110],
        [111, 112]]])

In [ ]:
a1 = np.array([1, 3, 5, 7, 9])
a2 = np.array([10, 30, 50, 70, 90])
a3 = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])


In [ ]:
a3 + [[100],
      [200],
      [300]]


array([[101, 102, 103],
       [204, 205, 206],
       [307, 308, 309]])

In [ ]:
a3 + [100, 200, 300]

array([[101, 202, 303],
       [104, 205, 306],
       [107, 208, 309]])

In [ ]:
a3.min(axis = 0)

array([1, 2, 3])

In [ ]:
a3.min(axis = 1)

array([1, 4, 7])

In [ ]:
a3.min(axis = 1, keepdims = True)

array([[1],
       [4],
       [7]])

In [ ]:
a3.max(axis = 0)

array([7, 8, 9])

In [ ]:
a3.max(axis = 1)

array([3, 6, 9])

In [ ]:
a3.max(axis = 1, keepdims = True)

array([[3],
       [6],
       [9]])

In [ ]:
A1 = np.array([2, 4, 6, 8]).reshape(2, 2)

In [ ]:
print(A1)

[[2 4]
 [6 8]]


In [ ]:
A2 = np.array([3, 5, 7, 9]).reshape(2, 2)

In [ ]:
print(A2)

[[3 5]
 [7 9]]


In [ ]:
A1.dot(A2)

array([[ 34,  46],
       [ 74, 102]])

In [ ]:
np.dot(A2, A1)

array([[ 36,  52],
       [ 68, 100]])

In [ ]:
A1 * A2

array([[ 6, 20],
       [42, 72]])

In [ ]:
np.transpose(A1)


array([[2, 6],
       [4, 8]])

In [ ]:
A2.transpose()

array([[3, 7],
       [5, 9]])

In [ ]:
A2.T

array([[3, 7],
       [5, 9]])